import './globals.css'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

import MainHeader from '@/components/headers/headerMain'
import AuthHeader from '@/components/headers/headerAuth'

export const metadata = {
  title: 'TheCirculArt',
  description: 'Generated by TheCirculArt',
}

export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  // console.log({ user })
  return (
    <html lang="es">
      <body className="grid grid-cols-1 divide-y">
        <header className="w-full p-2 md:p-8 bg-background ">
          <nav className="h-16">
            {user ? <MainHeader email={user.email} /> : <AuthHeader />}
          </nav>
        </header>
        <main className="w-full min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  )
}
