import './globals.css'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

import MainHeader from '@/components/headers/headerMain'
import AuthHeader from '@/components/headers/headerAuth'

export const metadata = {
  title: 'TheCirculArt',
  description: 'Generated by TheCirculArt',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()
  console.log('USER----->', user)
  return (
    <html lang="es">
      <body>
        <main className="w-full min-h-screen bg-background flex flex-col items-center">
          <nav className="w-full p-8">
            {user ? <MainHeader user={user} /> : <AuthHeader />}
          </nav>

          {children}
        </main>
      </body>
    </html>
  )
}
