import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import AuthHeader from '@/components/headers/headerAuth'

export const metadata = {
  title: 'TheCirculArt',
  description: 'Generated by TheCirculArt',
}

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  return (
    <main className="min-h-screen bg-background flex flex-col items-center">
      <div className="w-full h-full flex flex-col items-center">
        <nav className="w-full flex justify-center border-b border-b-foreground/10 h-16">
          {user && <AuthHeader user={user} />}
        </nav>
      </div>

      {children}
    </main>
  )
}
